---
title: "lit review section"
format: html
editor: visual
---

## Literature

### AR

The next generation of advanced technologies for learning include many different kinds of virtual reality (VR) and augmented reality (AR) and mixed reality (MR) applications. These related technologies have different affordances for educational purposes, but at their core they all allow for increased immersion into novel topics and concepts and new ways for students to interact with three-dimensional objects and places. Additonally, AR has shown the potential to enable individuals construct new understanding by laying digital displays over real-world environments[@yoonHowAugmentedReality2020]. By doing that , these AR experiences can help users inquire and explore aspects of a virtual world in more concrete ways that might not be possible in a naturalistic setting [@yoonHowAugmentedReality2020]. AR technologies are only recently starting to become more mainstream as technology becomes more affordable and more research is done into the affordances of AR within education. These affordances may include: scientific spatial ability(manipulating objects and content in a 3D space); engaging in scientific inquiry through the use of observations, questions, group collaboration, investigations and interpreting data; increased concpetual understanding of abstract concepts and invisible phenomena. <!--# need to cite dunleavy & dede 2014; cheng and tsai 2013; wu et al 2013 --> These are example affordances that can be used with AR to align instructional material with classroom learning goals such as allowing students to work together in pairs or small groups with a shared virtual object projected into their normal classroom space. <!--#  sentence needs work to connect it back to an example of aligning the affordances of AR to a realworld classroom context -->

<del>At the same time, the Framework for K-12 Science Education (NRC, 2012) and the resulting Next Generation Science Standards are asking teachers and students to integrate crosscutting concepts and science practices into their instruction. From research on early implementations of NGSS-aligned curricula, we know that the crosscutting concepts in general and issues surrounding scale in particular, are difficult concepts for teachers to integrate into their lessons and for students to understand using traditional materials (e.g., Harris et al., 2015). The crosscutting concept *Scale, Proportion, and Quantity* sits at the intersection of a traditionally difficult concept to teach with high overlap of the affordances of AR technologies (allowing for multiple perspectives of a virtual object, being able to superimpose a virtual object into a physical space). This pilot project will explore ways in which we can design and support AR experiences for middle school students that will engage them in the crosscutting concept of scale across different domain areas.</del>

Immersive digital environments have the potential to scaffold experiential learning activities that are often impractical or impossible to implement in a classroom setting (cite- lai et al 2020). Due to the ubiquitous nature of computing, AR(XR?)  has increasingly become more affordable compared to other immersive digital environments using virtual reality and other modalities.  (XR) In science education,  AR provides rich opportunities to motivate students by utilizing physical and digital objects that can create novel learning experiences for students.  AR also provides opportunities for distance learning in classrooms, which can reduce chances of students missing out on collaborative learning environments. In Dunleavy et al, 2009, researchers studied student interactions in Alien Contact! That combined physical and digital artifacts through the use of a handheld device, which can require students when interacting with these objects to inquire about mathematics, literacy and science understanding. This would be an example of an  affordance that can foster engagement with instructional content and a physical space.  Augmented reality presents several unique affordances when compared to similar technologies, such as: accessibility, affordability and ease of transport when compared to other mixed-reality devices.  Due to the ubiquity of computing and mobile devices and  growing advancements in devices that utilize GPS, WIFI, Lidar  and multimedia can all be leveraged towards educational technology that can enhance learning( Heinecke et al.,  2001). Because of this, it is becoming increasingly more affordable for institutions to implement AR technology in the classroom, without the need of expensive equipment.

### Scale

Scale, proportion & quantity is an important area in science & engineering that is fundamental to how students make observations and relationships in nature. Its critical for students to be able to distinguiqsh relative differences in size, time and energy scales and the ability to understand the proportional relationships in those quantities as the scales begin to change. This is just one example in science education of a cross cutting concept that educators and learners have struggles with in the classroom.

In science education, scale is important across domains such as astronomy and chemistry, where it is important to understand relative sizes and distances of observable and non observable artifacts.An example of this could be introducing an AR environment to  help students with seeing and understanding scale in different ways than can be traditionally  observed in a classroom environment.  The artifacts under investigation can be manipulated in different ways, including size and scale, allowing different viewpoints by walking around a virtual artifact and comparing it with real objects. 

<del>Current literature on scale understanding is focusing on VR simulations to help students navigate inaccurate understandings about size and scale. In science education, scale is important across domains such as astronomy and chemistry, where it is important to understand the relative sizes and distances of observable and non-observable artifacts at the extremes of scale.</del>

### Scale is hard to teach/learn

The cross cutting concept(CCC's) of scale, proportion and quantity is one of several  CCC's that is part of the new vision for k-12 science education (NRC, 2012). Scale is defined as  "a system of measurement that allows for the comparison of relative sizes" (Delgado et al ., 2007) these systems of measurement can include weight, time, temperature and other variables that can be assessed and estimated. Existing

In STEAM, understanding the concept of scale **is crucial to understanding relationships**.  Scale is particularly important in science disciplines such as astronomy, where spatial scale is important for students to understand the relative sizes, volumes, and distances of objects in the solar system and beyond. Scale is also important across the disciplines of geology (eg., geological time scales) and chemistry (eg., molecular and atomic scales) all have substantive concepts that involve issues at the extremes of scale 

While accurate measurement when quantifying known phenomena is highly important in the sciences, students have issues understanding scale (Jones et al., 2017)across different scientific domains. For my research, I am focused on students' understanding of the extremes of scale. Jones et al (2017) highlighted that students' ability to conceive of scale is limited by their age, education, and maturity(difficulties with objects beyond human scale).

When the context of scale is applied to the size of objects, young learners struggle to comprehend objects beyond the human scale (their own body) but can improve as they get older. For objects larger than human scale, young learners' conceptual ideas of objects "larger than them" can be the size of a school bus or minivan (Jones et al., 2017). As students get older (ie., high school students), their conceptual benchmark of larger units grows to larger objects like shopping malls or a football field (Ibid.) In the other direction, young learners have a very broad understanding of smaller objects ---- an ant or a fly might be the smallest thing they can conceptualize; older students can conceptualize objects at the microscopic level like blood cells or complex molecules (Tretter et al., 2006). For students to conceptualize scale they need a deeper understanding of the relative sizes of objects and entities at the extremes (bigger or smaller) which can be leveraged using the existing affordances of AR (eg., limited immersion) embodied learning activities within an AR simulation.

### AR and Collaborative Learning

Collaborative learning research..

I would  describe collaborative learning as an educational approach that involves effort among teachers and students that encourages them to complete tasks together.Building on Vygotsky's sociocultural theories that learning takes place through interactions and communication with others, and the importances of social environments  in the learning process. In research, collaborative learning is categorized as " A instructional use of small groups for students to work together to maximize learning" (Johnson et al., 1990)   Collaborative learning is accomplished through students working in groups while trying to mutually understand solutions, meanings or creating artifacts(Lin 2015). In contrast, individual learning is the more traditional learning that has occurred in classrooms throughout history, where classroom content, instructional content and learning pace are entirely based on a students ability and interest to increase knowledge. 

There are significant differences between collaborative and individual learning.  Collaborative learning requires students  and teachers to partake in social interactions, transferring of ideas and intergroup dynamics, which can be more advantageous over individual learning.  An example of this is Problem-based learning(PBL), a form of collaborative learning that utilizes  a student-centered approach so students can learn and interact in groups about a subject and solve complex open-ended problems. PBL is  commonly used in teaching medical students how to solve problems in a clinical setting, but is often being implemented in K-12 Education to help instructors facilitate student problem-solving and self-directed learning skills(Barrows & Kelson 1993).  PBL highlights a distinct difference between individual learning and collaboration, which is the role of the teacher. In problem-based learning teachers are often facilitating and fostering discussions in the classroom, as opposed to simply lecturing and assigning individual tasks for students. PBL, which is based on situated learning  is based on the idea that learning is effective when it is ingrained in learning that is anchored in everyday context(Hung et al ., 2008)

Augmented reality can be helpful in supporting collaborative learning, through the creation of immersive hybrid learning environments that combine real and virtual objects. As a result, AR can help facilitate problem solving, critical thinking and communication through collaborative learning activities. Within an educational context, AR can help support collaborative learning by allowing students to simulate training medical students(Hanna et al., 2018), or by allowing students to understand abstract science concepts like molecular structures(Bonete et al ., 2019).Augmented reality can help facilitate a community of learners by  integrating positive interdependent learning by giving students different or incomplete data that require group collaboration to solve a problem(Squire & Kloper, 2007). Integrating AR within the course curriculum can help science understanding, by allowing instructors to better  specific science phenomena, and allow students to interact with physical objects that can display contextual information, and allow students to manipulate objects in a 3-dimensional space. 

Instructors face several challenges when implementing AR technology in collaborative spaces. As previously mentioned, instructors cannot simply adopt technology in the classroom without additional support and training.  Successfully implementing AR technology in the classroom requires a knowledgeable instructor to properly introduce and facilitate these collaborative explorations, which may require multiple facilitators  if technical errors may occur. There is a need to create teacher materials to support implementing technology in the classroom while also finding ways to integrate other parts of the curriculum that the teacher is already using. With the goal of using AR as an effective learning tool in the classroom, there is a need to scaffold student exploration and 3-d object manipulation that is  based on clear parameters so that learning goals can be achieved in a short period of time. In addition to the creation of learning materials for teachers, there is a need for designers and educators to be less focused on what students are seeing in the application and more about the manipulations the students are doing within the application and how the students have learned from it. 

There are also practical and logistical challenges of implementing AR technology in the classroom, depending on the type of AR hardware being used, which can be cost prohibitive for schools to implement, manage and debug issues, which can pile increasing demands on teachers and administrators.  In regards to student learning, there are challenges relating to cognitive overload (Dunleavy et al., 2009) where students can feel overwhelmed if constructed environments and exercises are too complex. Managing the level of complexity for learners is a challenge that requires researchers to create a simple and dynamic learning experience; ability to scaffold experiences and limiting AR interactions by students(Squire & Kloper, 2007; O'shea et a., 2009).  

Another limitation of AR technology in the classroom is practicality. There are challenges in integration and managing this technology for researchers & instructors, but there are also institutional challenges.  AR technology is often best applied in student joint exploration, inquiry-based activities and informal learning, which can be different from standards-driven context of school systems. AR collaborative learning environments are time consuming and can be difficult to manage, and may often transfer to achievement or assessment testing metrics. 

\
\## Current space of science education within AR for k-12 learners

In extant literature, educational researchers have been creating inclusive field trips using augmented or virtual reality (Gilley et al., 2015). In a study with environmental science, Kamarainen and colleagues integrated AR technology water measurement equipment (using the Texas Instrument Nspire) and the FreshAiR augmented reality mobile application. The project "EcoMOBILE", students utilize their mobile device and water measurement device to collect water samples during a field trip. In this mixed-methods research design, researchers assessed students' self-efficacy on their ecological science knowledge, and tasks they completed during the field trip. Results from their study found that students showed an increased ability in understanding of how to complete science related tasks & understanding focal topics (Kamarainen et al., 2013). By combining AR technology with scientific measuring equipment and creating meaningful activities, students are provided with meaningful context in a field trip experience (Kamarainen et al., 2013).

<!--# Need to add susan yoon stuff & other informal learning things in museums -->

### Embodied Cognition

### Existing Methods for AR in science education

### Problem Space

###  Research Design/Plan

This research proposal aims to design and support AR collaborative learning experiences for middle-school students that engages them in the crosscutting concept of scale across different science domains. This project will employ a design-based research approach (dbr cite), which includes an iterative cycle of design, development, testing and refinement with input from instructors and students. Researchers and instructors will also iterate on supportive materials for teachers to best foster science discussion in the classroom using our learning technology (AR science activity).

As a secondary design principle, we will iterate on the design of this application using the Learning through Embodied Activity Framework (LEAF)\[\@danishLearningEmbodiedActivity2020\] to guide our science learning activity design. LEAF framework provides researchers educators tools for designing mixed reality learning experience, by looking at the roles of the student, teacher and collective groups within the activity itself. This framework will help us create activities that better grounds an embodied activity in the requisite learning goals for instructors and learners, while also highlighting different dimensions of an embodied activity (eg., individual and collective experiences for students and instructors).

<!--# This could use some work -->

Aligning to the below NGSS performance expectations will increase the likelihood that teachers will eventually be able to easily integrate the activities into their normal curricular materials and plans.

NGSS Scale performance Expectations:

● \[MS-PS1-1\](https://www.nextgenscience.org/pe/ms-ps1-1-matter-and-its-interactions): Develop models to describe the atomic composition of simple molecules and extended structures.

● \[MS-ESS1-3\](https://www.nextgenscience.org/pe/ms-ess1-3-earths-place-universe): Analyze and interpret data to determine scale properties of objects in the solar system.

<!--# could use some visuals for that  -->

## Broad Research Questions:

How can an AR learning environment support students in progressing in their understanding of objects and scientific phenomena at the extreme ends of scales?

-   In what ways do limited AR immersed environments support an embodied learning approach to instruction?\

-   What challenges teacher might face when implementing embodied AR activities in a science classroom?

-   specific design details? <!--# two main research questions and 1-2 sub questions fo these  -->

-   design featuresd?

    Features in the app? specific things we want facilators to do--- \> becuase are allows for layered information can distribute this two students diffferently -- contextualized in small group collabortive activity- this has to be in the RQ

the gains from this tech has to be situated within a particular context/student/

how does ar support distributed cognition/designing ways for in which to distrbuted cognition (each students have different scale aspects of the activity)

maybe the literature- these type of things are more beneficial for students; the AR is allow for differetn type of distribute of knowledge than before( can look into this) what can AR do that other things can do) can support a stronger argument --- limited immersive

## Target Group

The target group for this project is middle school students and instructors in rural middle school classrooms in the Midwest

## Project Plan and Timeline

This research proposal will develop a set of AR science activities around the concept of scale across different domains of science (Astronomy and Biology) that will be helpful to middle school learners connect this crosscutting concept to different concepts and situations. The foundation for these AR activities will be around two Next Generation Science Standards (NGSS) performance expectations and the LEAF framework. Additionally this project will employ a design-based research approach [@fishmanDesignbasedImplementationResearch2018] which includes several iterative cycles of design, development, refinement and testing of activities and supportive materials for instructors

### Timeline

#### Spring 2023 - Design

Begin the development of two AR-based collaborative science activities which will take place during summer 2023 with middle-school learners. We will begin early iterations of lessons plans for instructors on how to integrate the activity into their curriculum.

In conjunction with this we will begin development of our AR app with, with the two aforementioned activities(will be aligned with current middle school curricula). This AR application will be developed using the iOS ARKit3 and iPad Pros. Additionally, this project will employ

#### Summer 2023- Create

#### Fall 2023- Iterate & revisions & testing again

#### Spring 2024 - Writing thisup

## Methods

### Procedure 

In these activities students will be learning about scale in a variety of different contexts around the concept of size and scale (possibly maps and models) to help conceptualize relationships between objkects and phenomena in a naturalistic setting. They will be learning about the relative differences in sizes of bjects relating to planets & stars, and the size of atoms and molecules.

These activities will be two collaborative sessions spanning 30 minutes each in an after school lab sessions at CRC(our lab). In this activity students will collaboratively create scale models and be introduced to science simulations. In the first activity, students will be introduced to planets within our solar system (8?) within an AR environment (mobile tablet with AR app) where students will be able to explore different planets and distances

Scale models:\
Science Simulations:

### Example Activities

| Activity/Task | Task Instruction | Col3 |
|---------------|------------------|------|
|               |                  |      |
|               |                  |      |
|               |                  |      |

: Example AR Activities

### Data Collection

Data will be collected using telemetry (log data) from the mobile application (iPad Pros); Virtual notebooks to create and project annotations; Semi-structured interviews at conclusion of each activity ; Field notes; Audi & video will be recording using GoPro cameras.

We will transcode video recordings alongside the field notes and structured interviews to create a qualitative code scheme (e.g., student engagement, ease of app use, learning gains from activity) and additional log data.\]

### Interviews

To better understand the affordances of AR on science learning, we will conduct semi-structured interviews with all students to probe what aspect of the augmented learning activity helped them grasp the concept of scale. We pose a few questions:

### Field Notes

Within our AR application, students will have access to a virtual notebook to make collaborative observations and inferences about different artifacts in their virtual environment. Students will be able to project these annotations and objects on a shared physical space, where students and instructors can make public comments and additional observations.

### Lesson plans

We will be creating lesson plans...

Pre and post intervention survey

We will be conducting pre and post tests on student knowledge of scale concepts in our solar system and complex molecules

### Iterative Design Feedback

## Design Guidelines

### Design for a collective AR activity of a collective phenomena + DBR

at least three sessions?\
\## DBR

----pick popular curriculu and see what they're doing -- loooking at local schools

convince teachers to do this-- and match timeline with the curriculum? --Ping rob with this on curriculum; After school (Could do work at the crc?)\
Whats going to happen with covid?

Labels/Designs etc; annotations\
Pre/post test

### Things i've done in the past

### Things i need to do

### Analysis

Researchers will be analyzing field notes, semi structured\
interviews, virtual notebooks, and video data (within IRB appointed guidlines on recording).\
Looking at student learning, the analysis will consist of qualitative coding of observations of student interactions during class as well as input from the teacher interviews. We will code the classroom data for evidence of student learning of the target science core ideas, practices, and crosscutting concepts. We will also code the data for information about how students interacted with the AR application itself and challenges the teachers might have had with managing this newer technology.

### Hypothesis

A few of the learning hypotheses we are looking at in this research proposal are 1. How do students in a collaborative group interact within a given science activity; and how do they reconcile with scale differences within our app?

### Learning Outcomes

Students will be able to (better?)? developmental models at the extremes of scale across the topics of simple molecules, extended structures, and understand scale properties of objects in the solar system.

### Dissemination plan

## IRB

### Recruitment

Students and instructors will be recruited from a local middle school in the Midwest, with a total of 40 students ranging from grade 5-8th. We will be recruiting up to four instructors to help in lesson plan development and AR activity implementation. Instructors will be compensated 100 dollars each.

### Excusion criteria --\> something that needs to be done

BVI? what will work for most students?

can be an additional thing? What types of things might be included to be more inclusive?

what are students learning/engaging/small groups (pairs vs groups of 3)\-\-- more student focused(more clarity)

\
\

## 
